POST http://localhost:3000/file/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="item2.png"
Content-Type: image/png

< ./item2.png

--boundary--
