version: '3.9'
services:
  guitar.user.mongo:
    image: mongo:4.4
    restart: always
    container_name: guitar.user.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}

    ports:
      - 27017:27017

    volumes:
      - guitar.mongo.user:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/${MONGODB_DATABASE} --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  guitar.user.mongo.ui:
    image: mongo-express
    restart: always
    container_name: guitar.user.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@guitar.user.mongo:27017/

  guitar.blog.postgres:
    image: postgres:14-alpine
    container_name: guitar.blog.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - guitar.postgres.blog:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - guitar.blog

  guitar.blog.pgadmin:
    image: dpage/pgadmin4
    container_name: guitar.blog.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 8083:80
    depends_on:
      - guitar.blog.postgres
    networks:
      - guitar.blog

networks:
  guitar.blog:
    driver: bridge

volumes:
  guitar.mongo.user:
  guitar.postgres.blog:
